// Portfolio data for Jathurshan Thadchanamoorthy
// Distilled from local data files in portfolio-jathur/data/

window.PORTFOLIO_DATA = {
  person: {
    name: "Jathurshan",
    fullName: "Jathurshan Thadchanamoorthy",
    title: "software · devops · ai/ml",
    location: "sri lanka",
    statement: "I build and ship reliable systems — from the database to the deploy pipeline. Some have models in them. A few run on-chain.",
    bio: [
      "I'm a computer engineering undergraduate at the University of Ruhuna and currently a software engineer intern at IronOne Technologies, where I help build the Primary Dealer System used by Sri Lanka's fintech sector. I write Quarkus on the backend and React + TypeScript on the front.",
      "My work spans more than one lane. On the platform side: Docker, Kubernetes, AWS, Jenkins pipelines, Nginx tuning — the unglamorous wiring that keeps services alive. On the ml side: a published paper on employee-turnover prediction (ensemble KNN + Random Forest), the Stanford ML specialization, and a TensorFlow habit. And on the chain side: Hyperledger Fabric and a bit of Solidity, mostly out of curiosity for what permissioned ledgers can actually solve.",
      "Add competitive programming on top — 19th nationally and 245th globally at IEEE Xtreme '24, 5th at HaXtreme 3.0. I care about systems that hold up under real load: secure auth, sensible APIs, observability you can actually read. Less about novelty, more about the thing not breaking at 2am."
    ],
    email: "ktmjathur2001@gmail.com",
    socials: {
      github: "https://github.com/jathurT",
      linkedin: "https://linkedin.com/in/jathurt",
      leetcode: "https://leetcode.com/ktmjathur2001",
      medium: "https://medium.com/@jathurt"
    },
    intern: "currently interning @ IronOne Technologies",
    timezone: "Asia/Colombo",
  },

  facts: [
    { v: "3.91", l: "GPA / 4.0 · UoR" },
    { v: "8,784", l: "Teams beaten at IEEE Xtreme" },
    { v: "23+", l: "Certifications shipped" },
    { v: "6 mo", l: "Building fintech @ IronOne" },
  ],

  experience: [
    {
      company: "IronOne Technologies",
      role: "Software Engineer Intern",
      dates: "may 2025 — nov 2025",
      summary: "Built the Primary Dealer System for Sri Lanka's fintech sector. Quarkus services, React + TS front, code reviews, and an indecent amount of debugging Keycloak.",
      stack: ["Quarkus", "Java", "React", "TypeScript", "PostgreSQL", "Keycloak"],
    },
    {
      company: "University of Ruhuna",
      role: "Computer Engineering · undergraduate",
      dates: "2022 — present",
      summary: "BSc Computer Engineering, GPA 3.91 / 4.0. Concentrating on distributed systems, machine learning, and applied cryptography.",
      stack: ["C++", "Java", "Python", "Systems", "Networks", "Algorithms"],
    },
    {
      company: "IEEE Xtreme 24h",
      role: "Competitive Programmer · 19th national / 245th global",
      dates: "oct 2024",
      summary: "Solo'd against 8,784 teams over 24 hours of algorithmic problems. Sleep, optional. Caffeine, mandatory.",
      stack: ["C++", "Python", "Algorithms", "Problem Solving"],
    },
    {
      company: "HaXtreme 3.0",
      role: "Hackathon · 5th place",
      dates: "2024",
      summary: "5th of 93+ teams. Built and shipped a full prototype in under 36 hours.",
      stack: ["Full Stack", "React", "Node", "Speed"],
    },
  ],

  featured: [
    {
      year: "2025",
      title: "Student Management System",
      desc: "Enterprise-grade student platform — enrollment, scheduling, attendance — wired through a four-tier RBAC and Keycloak identity layer.",
      stack: ["Java", "Quarkus", "TypeScript", "PostgreSQL", "Keycloak", "Docker"],
      live: null,
      github: "https://github.com/jathurT/SMS-backend",
      mock: "sms",
    },
    {
      year: "2024 — 2025",
      title: "DN Dental Clinic Platform",
      desc: "Full-stack booking and patient management for a multi-location dental practice. Spring Boot, JWT auth, Dockerized on AWS, Jenkins CI/CD.",
      stack: ["Spring Boot", "React", "MySQL", "AWS", "Docker", "Jenkins"],
      live: null,
      github: "https://github.com/jathurT/jathurT-DN-Dental-Clinic-Backend",
      mock: "dental",
    },
    {
      year: "2024",
      title: "Employee Turnover Prediction",
      desc: "Ensemble of KNN + Random Forest classifiers for HR retention. Feature engineering, hyperparameter tuning, and a paper on ResearchGate.",
      stack: ["Python", "Scikit-Learn", "Pandas", "Random Forest", "KNN"],
      live: "https://www.researchgate.net/publication/387298065",
      github: "https://github.com/jathurT/Employee-Turnover-Prediction-ML",
      mock: "ml",
    },
    {
      year: "2024 — 2025",
      title: "Hotel Booking · Microservices",
      desc: "A distributed booking platform — user, booking, payment, inventory — each independently deployable, talking through an API gateway with service discovery.",
      stack: ["Spring Boot", "Microservices", "PostgreSQL", "Eureka", "API Gateway"],
      live: null,
      github: "https://github.com/jathurT/Hotel-Booking-Web-Application-Backend-Microservice-",
      mock: "hotel",
    },
  ],

  archive: [
    { year: "2025", title: "Real-Time Network Monitoring Tool", stack: ["Java", "JavaFX", "Sockets"], github: "https://github.com/jathurT/Socket-Programming-Project" },
    { year: "2024", title: "E-Commerce Web Application", stack: ["Spring Boot", "React", "MySQL", "JWT"], github: "https://github.com/jathurT/eCommerce-Spring-Boot" },
    { year: "2024", title: "Point of Sale System", stack: ["C#", "WPF", "SQLite"], github: "https://github.com/jathurT/WPF-POS-System-Master" },
    { year: "2024", title: "Blood Bank Management System", stack: ["SQL", "Stored Procedures", "Indexing"], github: "https://github.com/jathurT/Blood-Bank-Management-System-RDMS" },
    { year: "2025", title: "Spring Boot Actuator deep-dive", stack: ["Spring Boot", "Observability"] },
    { year: "2025", title: "Spring AI experiments", stack: ["Spring AI", "LLMs", "Vector DB"] },
    { year: "2024", title: "Neural Networks & Deep Learning (cert.)", stack: ["TensorFlow", "Backprop"] },
    { year: "2025", title: "Go fundamentals (HackerRank Basic)", stack: ["Go", "Concurrency"] },
    { year: "2025", title: "JUnit + Mockito unit-testing playbook", stack: ["JUnit", "Mockito", "TDD"] },
    { year: "2025", title: "Stanford ML specialization", stack: ["Supervised", "Unsupervised", "RL"] },
  ],

  skills: [
    { cat: "Backend", items: [["Java", "3y"], ["Spring Boot", "2y"], ["Quarkus", "1y"], ["Node.js", "2y"], ["Go", "1y"], ["Python", "3y"]] },
    { cat: "Frontend", items: [["React", "3y"], ["Next.js", "2y"], ["TypeScript", "2y"], ["Tailwind", "2y"]] },
    { cat: "Data", items: [["PostgreSQL", "2y"], ["MySQL", "3y"], ["MongoDB", "2y"], ["Oracle", "1y"], ["Neo4j", "1y"]] },
    { cat: "Infra", items: [["Docker", "2y"], ["AWS", "2y"], ["Jenkins", "2y"], ["Kubernetes", "1y"], ["Nginx", "1y"]] },
    { cat: "ML / Data", items: [["Scikit-Learn", "2y"], ["TensorFlow", "1y"], ["Pandas / NumPy", "2y"]] },
    { cat: "Web3", items: [["Hyperledger Fabric", "6mo"], ["Solidity", "6mo"], ["Ethereum", "6mo"]] },
  ],

  recommendations: [
    {
      name: "Durshika Balaraja",
      role: "Senior Technical PM",
      company: "IronOne Technologies",
      relationship: "Direct Manager",
      initials: "DB",
      tint: "violet",
      date: "Nov 20, 2025",
      pull: "An outstanding contributor — dependable, proactive, open to feedback.",
      quote: "I had the pleasure of supervising Jathurshan during his internship as a Software Engineering Intern, and I can confidently say he has been an outstanding contributor to our team. From the very beginning, he showed strong enthusiasm to learn, take ownership, and consistently improve his skills. He quickly adapted to our technical environment and delivered his tasks with focus, responsibility, and attention to detail. His ability to grasp both the technical and functional aspects of the work was impressive for someone at an intern level.",
      featured: true,
    },
    {
      name: "Rashmi Prabhath",
      role: "Lead Software Engineer",
      company: "IronOne Technologies",
      relationship: "Mentor",
      initials: "RP",
      tint: "emerald",
      date: "Dec 15, 2025",
      pull: "Delivered on time — even in the hardest situations.",
      quote: "Consistently impressed by his technical depth and quick learning curve. He demonstrated a professional attitude and a remarkable ability to deliver requirements on time, even when faced with challenging situations. Jathurshan went beyond expectations by putting in extra effort to ensure project success.",
    },
    {
      name: "Irantha Thilakarathna",
      role: "Technical BA",
      company: "IronOne Technologies",
      relationship: "Colleague",
      initials: "IT",
      tint: "amber",
      date: "Dec 7, 2025",
      pull: "Operated at a Software Engineer level, not an intern level.",
      quote: "Unlike a typical intern who performs only assigned tasks, he consistently operated at a Software Engineer level — taking full ownership, proactively identifying solutions, and delivering beyond expectations. Highly solution-oriented, always willing to explore alternatives and refine approaches.",
    },
    {
      name: "Haathim Munas",
      role: "Software Engineer",
      company: "IronOne Technologies",
      relationship: "Colleague",
      initials: "HM",
      tint: "sky",
      date: "Nov 22, 2025",
      pull: "Always asking the right questions.",
      quote: "From the first day onwards, Jathurshan impressed us with his technical skills. He was always asking the right questions, which helped him improve as well as contribute to the project. He was always responsible with his work and committed immensely.",
    },
    {
      name: "Shanilka Madushan",
      role: "Software Engineer",
      company: "IronOne Technologies",
      relationship: "Colleague",
      initials: "SM",
      tint: "coral",
      date: "Nov 20, 2025",
      pull: "Stood out as a promising Software Engineer.",
      quote: "He consistently completed his tasks with accuracy and professionalism. Jathurshan collaborated exceptionally well with QA and Business Analyst teams, communicating clearly and contributing meaningful ideas.",
    },
    {
      name: "Sukumar Kavishan",
      role: "Software Engineer",
      company: "IronOne Technologies",
      relationship: "Colleague",
      initials: "SK",
      tint: "rose",
      date: "Nov 17, 2025",
      pull: "Hard work, accountability, strong problem-solving.",
      quote: "Impressed by his hard work, accountability, and strong problem-solving ability. He consistently took ownership, quickly understood requirements, and delivered high-quality work with a positive attitude.",
    },
  ],

  writing: [
    { date: "2025.04", title: "What I learned wiring Keycloak into a four-tier RBAC", read: "8 min" },
    { date: "2025.02", title: "Quarkus vs. Spring Boot — six months later", read: "11 min" },
    { date: "2024.12", title: "Ensemble methods for turnover prediction: a postmortem", read: "14 min" },
  ],
};
